"""The RefinementHead's settings, kept out of config.py on purpose.

config.py describes the VQ model: the ViT towers, the codebook, the corpus,
the schedule every run has followed since the project started. The refinement
head is a later, optional stage bolted onto the end of the decoder, with its
own architecture, its own training modes and its own learning rate, and mixing
its fields in among the VQ ones would make the boundary between "the model"
and "the thing attached to the model" invisible.

VQGANTrainConfig holds one of these as a nested field (`cfg.refine`), which is
the one direction the two files depend on each other. Its CLI flags follow the
same nesting: --refine-<field>, generated by parse_args() in
scripts/train_vqgan.py.
"""

from dataclasses import dataclass


@dataclass
class RefineConfig:
    """Everything about the post-decoder RefinementHead.

    Two kinds of knob live here, and they do not end up in the same place:

      - `enabled` / `hidden_channels` / `num_blocks` define the network's
        shape, so they go into VQGANTrainConfig.model_config() and are written
        into every checkpoint. Change one and an existing checkpoint will not
        load.
      - `train_stage`, `warmup_steps` and the five learning-rate fields are
        training hyperparameters like disc_weight: they say what this
        particular run does to the head, they are not properties of the
        weights it produces, and they are not stored.
    """

    # ---- Architecture (stored in the checkpoint) ----
    enabled: bool = False
    hidden_channels: int = 64
    num_blocks: int = 2

    # ---- This run only ----
    #
    # Which half of the model gets gradients:
    #   "joint"       everything at once — the backbone and the head together
    #   "refine_only" the head alone, on top of a frozen backbone
    #   "vq_only"     the backbone alone, as if the head weren't there
    #
    # "refine_only" freezes the quantizer's codebook updates too, not just the
    # gradients: its EMA update and dead-code revival are gated on train/eval
    # mode rather than on requires_grad, and a backbone that is supposed to be
    # frozen should not keep drifting underneath the head.
    train_stage: str = "joint"
    # ---- The head's learning rate, and the schedule it decays on ----
    #
    # 0 = the head simply rides the generator's rate: one param group, one
    # cosine curve, and the three fields below never come into play. Above 0
    # the head gets its own optimizer param group *and* its own copy of the
    # whole schedule, because a head bolted onto a backbone that is 3M images
    # into its decay would otherwise be born at whatever near-min_lr rate that
    # schedule has already reached.
    #
    # Each of the four reads 0 (or "") as "whatever the VQ side does", so a
    # head given only an `lr` still follows the familiar curve shape, and every
    # divergence from it is something written down on purpose.
    #
    # What makes a separate copy worth having is not a separate clock — there
    # is one counter for the run, images_seen, and both rates are read off it.
    # It is that the two are at different points in their own lives at the same
    # reading: a head attached to a 3M-image backbone is on its first image
    # while the backbone is deep into its decay, so the ramp length and the
    # endpoint that suit one are not the ones that suit the other.
    lr: float = 0.0
    # How `lr` above is scaled for the batch this run actually uses — the same
    # three rules VQGANTrainConfig.lr_scaling offers ("sqrt" / "linear" /
    # "none"), applied by the same code, so a refine rate quoted here means the
    # rate at reference_batch_size exactly as the VQ one does. "" = the rule
    # the VQ side is using.
    lr_scaling: str = ""
    # The floor the head's decay never goes below. 0 = the VQ side's min_lr. A
    # floor of exactly zero is therefore not expressible here; ask for 1e-12 if
    # you ever want one.
    min_lr: float = 0.0
    # The image count at which the head's decay reaches min_lr. 0 = the VQ
    # side's end_steps_lr. Worth setting explicitly on a refine run much
    # shorter than a full VQ one: an endpoint left at 3.4M images means a
    # 200k-image run only ever walks the first, nearly flat 6% of the cosine,
    # so its rate barely decays at all.
    end_steps_lr: float = 0.0
    # How long the head's rate ramps linearly from 0 before its cosine starts.
    # 0 = the VQ side's lr_warmup_steps; for a ramp of effectively nothing
    # while the VQ side keeps one, ask for 1 rather than 0.
    #
    # Measured, like everything else here, in images_seen — which is the run's
    # counter, not the head's age. The two coincide on the path that attaches a
    # head with --vqgan-checkpoint, where images_seen restarts at 0. They do
    # not on a --resume that attaches a head to a checkpoint already millions
    # of images in: images_seen is past any warmup on arrival, so the head
    # starts at its full rate however this is set. Zero-init makes that far
    # less alarming than it sounds — the head begins as an exact identity — but
    # --vqgan-checkpoint is the path that gives it a warmup at all.
    lr_warmup_steps: int = 0
    # 0 = train_stage stays whatever it was set to for the whole run. Above 0,
    # a "refine_only" run flips to "joint" once this many images have gone
    # through — the same shape of trigger as ema_warmup_steps: settle the head
    # against a frozen backbone first, then let the two adapt to each other.
    warmup_steps: int = 0

    STAGES = ("joint", "refine_only", "vq_only")
