"""The RefinementHead's settings, kept out of config.py on purpose.

config.py describes the VQ model: the ViT towers, the codebook, the corpus,
the schedule every run has followed since the project started. The refinement
head is a later, optional stage bolted onto the end of the decoder, with its
own architecture, its own training modes and its own learning rate, and mixing
its fields in among the VQ ones would make the boundary between "the model"
and "the thing attached to the model" invisible.

VQGANTrainConfig holds one of these as a nested field (`cfg.refine`), which is
the only tie between the two files. Nothing here reads a value from there: the
head's schedule is written out in full below, and moving --lr or --end-steps-lr
does not move it. That is the point — the head is trained as its own thing, so
its settings are its own, and a number here means what it says rather than
"unless you also changed the other one".

The CLI flags follow the nesting: --refine-<field>, generated by parse_args()
in scripts/train_vqgan.py.
"""

from dataclasses import dataclass


@dataclass
class RefineConfig:
    """Everything about the post-decoder RefinementHead.

    Two kinds of knob live here, and they do not end up in the same place:

      - `enabled` / `hidden_channels` / `num_blocks` define the network's
        shape, so they go into VQGANTrainConfig.model_config() and are written
        into every checkpoint. Change one and an existing checkpoint will not
        load.
      - everything else — the stage, the learning-rate schedule, the loss
        weights, the adversarial settings, the eval cadence — says what this
        particular run does. None of it is a property of the weights it
        produces and none of it is stored in the checkpoint.

    The second group covers the same ground as the matching fields on
    VQGANTrainConfig and deliberately uses the same names, because a run picks
    one side or the other wholesale: a model with a refinement head trains by
    these, a model without one trains by VQGANTrainConfig's. So --disc-weight
    and --lpips-weight do not reach a refine run — --refine-disc-weight and
    --refine-lpips-weight do. Every default below starts equal to the VQ
    default it mirrors, so a run that sets nothing trains exactly as it would
    have; they are two separate knobs that happen to start in the same
    position, not one knob read twice.
    """

    # ---- Architecture (stored in the checkpoint) ----
    enabled: bool = False
    hidden_channels: int = 64
    num_blocks: int = 2

    # ---- This run only ----
    #
    # Which half of the model gets gradients:
    #   "joint"       everything at once — the backbone and the head together
    #   "refine_only" the head alone, on top of a frozen backbone
    #   "vq_only"     the backbone alone, as if the head weren't there
    #
    # "refine_only" freezes the quantizer's codebook updates too, not just the
    # gradients: its EMA update and dead-code revival are gated on train/eval
    # mode rather than on requires_grad, and a backbone that is supposed to be
    # frozen should not keep drifting underneath the head.
    train_stage: str = "joint"
    # ---- How long the head trains ----
    #
    # Counted in the head's own images, so it is a length and not a
    # destination: "train the head for 200,000 images", full stop, whatever the
    # backbone underneath has already seen.
    #
    # VQGANTrainConfig.max_steps cannot say that. It is an absolute position on
    # the run's clock, which is the right shape for the backbone — a schedule
    # that has been running since image 0 and ends at a fixed point — and the
    # wrong shape for a head created part-way through: asking for 200,000
    # images of refinement on a 1.4M-image model would mean typing 1,600,004,
    # a number that is mostly the backbone's history and says nothing about the
    # head. Worse, type the 200,000 you meant and the run ends before its first
    # step, because the clock is already past it.
    #
    # So the two budgets are read against the two clocks, and a run stops when
    # either one is spent: the backbone at VQGANTrainConfig.max_steps on
    # vq_images_seen, the head here on refine_images_seen. Under refine_only
    # only this one can be reached, which is what makes it the run's length.
    #
    # Left equal to end_steps_lr on purpose — a head whose rate lands on
    # min_lr exactly as its budget runs out — but nothing keeps them equal.
    max_steps: int = 200_000
    # ---- The head's learning rate, and the schedule it decays on ----
    #
    # A complete schedule, not a set of adjustments to the VQ one: the head
    # always gets its own optimizer param group, driven by the five fields
    # below and by nothing in VQGANTrainConfig. Raising --lr moves the
    # backbone and leaves the head where it is, and vice versa.
    #
    # Why a whole second copy rather than a shared curve: a separate clock as
    # well as a separate curve. The head has its own image counter, starting at
    # zero the moment it is created and advancing only on steps that actually
    # train it (see the three clocks in train_vqgan.main), so every field below
    # is read against the head's own age rather than the run's. A head added to
    # a 3M-image backbone really is on its first image while the backbone is
    # deep into its decay, and now the numbers say so: the rate, the ramp and
    # the endpoint that suit one are not the ones that suit the other. The
    # usual shape of that is the head learning an order of magnitude faster
    # than the converged trunk underneath it — the same arrangement as
    # fine-tuning a fresh head onto a pretrained network — and it cannot be
    # expressed at all with one rate, or one clock, .for both.
    #
    # The values here happen to start equal to the VQ defaults, so a run that
    # touches neither trains both halves on the same curve. That is a starting
    # point, not a link — nothing keeps them equal once either side moves.
    lr: float = 1e-4
    # How `lr` above is scaled for the batch this run actually uses — the same
    # three rules VQGANTrainConfig.lr_scaling offers ("sqrt" / "linear" /
    # "none"), put through the same scaled_lr(), so a rate quoted here means
    # the rate at reference_batch_size exactly as a VQ one does. Set
    # independently of the VQ rule; sharing the arithmetic is not sharing the
    # choice.
    lr_scaling: str = "sqrt"
    # The floor the head's decay never goes below.
    min_lr: float = 1e-6
    # The head's own image count at which its decay reaches min_lr — not the
    # run's, so this is simply "how many images the head trains for", and the
    # natural setting is the length of the refine run itself.
    #
    # The one most worth checking on a short run, because the cosine is at its
    # flattest right at the start: against a 3.4M endpoint a 200k-image run
    # walks the first 6% of the curve and its rate ends at ~99% of base, which
    # is a constant learning rate wearing a schedule's clothes. Adversarial
    # training has no minimum to settle into, so the thing that stops it
    # oscillating is the rate getting small — an endpoint far past the end of
    # the run means that never happens.
    end_steps_lr: float = 200_000
    # How long the head's rate ramps linearly from 0 before its cosine starts.
    # 0 = no ramp, straight in at the full rate.
    #
    # Measured, like everything else here, in the head's own images, which is
    # the whole reason the head has its own counter: a warmup has to measure
    # the age of the parameters it is ramping. Read against the run's counter
    # instead — as this did until the clocks were split — a head added to a
    # model already millions of images in would arrive past its own warmup and
    # start at full rate however this was set, and the path that adds a head
    # while keeping the model's history is now the ordinary one.
    lr_warmup_steps: int = 10_000
    # 0 = train_stage stays whatever it was set to for the whole run. Above 0,
    # a "refine_only" run flips to "joint" once the head has had this many
    # images — the same shape of trigger as ema_warmup_steps, and on the same
    # footing as the two fields above it: settle the head against a frozen
    # backbone first, then let the two adapt to each other. Counted on the
    # head's clock, which under refine_only is the only one moving anyway, so
    # the number means what it looks like it means either way.
    #
    # Not a warmup, despite sitting one field below one: lr_warmup_steps ramps
    # a number, this changes which parameters have gradients at all (and
    # rebuilds the optimizer around the new set). The two are independent and
    # can be set together — ramp the head's rate over the first 2,000 images,
    # let it train alone until 50,000 — which is exactly why they should not
    # have looked like two spellings of one knob.
    unfreeze_steps: int = 0

    # ---- Loss, adversarial and eval, for a run that has a head ----
    #
    # The reconstruction loss the head is trained against. Same three terms in
    # the same units as VQGANTrainConfig's, and worth reaching for on a refine
    # run because the artifact being chased is perceptual, not numerical:
    # patch seams are low-amplitude and high-frequency, so they cost almost
    # nothing in L2 and show up mostly in LPIPS. Raising lpips_weight here is
    # how to say that without touching the VQ side's balance.
    l2_weight: float = 1.0
    logit_laplace_weight: float = 0.1
    lpips_weight: float = 1.0
    use_lpips: bool = True
    # The adversarial term — the other thing that teaches the decoder to smooth
    # over patch boundaries, and the reason the same value on the VQ side has
    # been raised twice. The head's own scalar on top of the adaptive weight.
    #
    # Worth being conservative with here in a way the VQ side is not, because
    # the two have very different room to answer a discriminator. The decoder
    # proper can change what it draws; the head is a handful of 3x3 convs with
    # a receptive field around 13 pixels (6 layers at the default num_blocks),
    # which cannot alter structure at all. Asked to look more real, the only
    # move available to it is high-frequency texture, and pushed hard enough
    # that is what it produces — grain, spread evenly, ignoring the picture.
    disc_weight: float = 1.0
    # ...and its own warmup, on the head's own clock: a freshly created head
    # faces a discriminator that has already trained for millions of images and
    # wants longer before it starts taking its advice. This counts the head's
    # first images, so the number is the head's grace period rather than a
    # threshold the backbone wandered past long ago.
    disc_warmup_steps: int = 20_000
    # Gradient clipping for the step as a whole (see
    # VQGANTrainConfig.grad_clip_norm for the reasoning).
    grad_clip_norm: float = 1.0
    # How often the run stops to measure, in images. Worth lowering on a short
    # refine run — but note what the readout can and cannot see: it reports
    # val L1 and codebook statistics, and the head moves neither much. L1
    # barely registers a seam being removed, and in refine_only the codebook
    # is frozen outright, so its numbers sit still by construction. The
    # recon_img*.png previews written alongside are where the 8x8 grid either
    # is or is not, and scripts/test_whole_image.py is the before/after.
    eval_every_steps: int = 10_000

    STAGES = ("joint", "refine_only", "vq_only")
